/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Obsidian Baidu Netdisk Sync Plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BaiduSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings/settings.ts
var DEFAULT_SETTINGS = {
  appKey: "",
  appSecret: "",
  accessToken: "",
  refreshToken: "",
  tokenExpiresAt: 0,
  remoteBasePath: "/apps/obsidian_vault",
  syncOnStartup: true,
  syncIntervalMinutes: 10,
  syncOnSave: false,
  syncDebounceSeconds: 5,
  syncObsidianConfig: true,
  syncPlugins: true,
  syncThemes: true,
  ignoredPatterns: [
    "**/.git/**",
    "**/.DS_Store",
    "**/Thumbs.db",
    "**/workspace*.json",
    "**/cache/**",
    "**/indexeddb/**"
  ].join("\n"),
  concurrency: 3,
  enableE2EE: false,
  e2eePassword: "",
  lastSyncTime: 0
};

// src/settings/settingsTab.ts
var import_obsidian = require("obsidian");
var BaiduSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u767E\u5EA6\u7F51\u76D8\u540C\u6B65\u8BBE\u7F6E").setHeading();
    new import_obsidian.Setting(containerEl).setName("1. \u767E\u5EA6\u7F51\u76D8\u8D26\u53F7\u6388\u6743 (OAuth 2.0)").setHeading();
    const authDesc = containerEl.createDiv({ cls: "setting-item-description" });
    const p1 = authDesc.createDiv();
    p1.appendText("1. \u8BBF\u95EE ");
    const link = p1.createEl("a", { text: "\u767E\u5EA6\u7F51\u76D8\u5F00\u653E\u5E73\u53F0", href: "https://pan.baidu.com/union" });
    link.setAttr("target", "_blank");
    p1.appendText(" \u767B\u5F55\u5E76\u521B\u5EFA\u4E2A\u4EBA\u5F00\u53D1\u8005\u5E94\u7528\u3002");
    const p2 = authDesc.createDiv();
    p2.appendText("2. \u83B7\u53D6\u5E94\u7528\u7684 ");
    p2.createEl("b", { text: "AppKey" });
    p2.appendText(" \u4E0E ");
    p2.createEl("b", { text: "AppSecret" });
    p2.appendText(" \u5E76\u586B\u5165\u4E0B\u65B9\u3002");
    const p3 = authDesc.createDiv();
    p3.appendText("3. \u70B9\u51FB\u201C\u83B7\u53D6\u7F51\u9875\u6388\u6743\u7801\u201D\uFF0C\u5728\u5F39\u51FA\u7684\u9875\u9762\u767B\u5F55\u5E76\u6388\u6743\uFF0C\u5C06\u7F51\u9875\u8FD4\u56DE\u7684\u6388\u6743\u7801\u7C98\u8D34\u81F3\u4E0B\u65B9\u6362\u53D6 Token\u3002");
    new import_obsidian.Setting(containerEl).setName("AppKey (Client ID)").setDesc("\u5F00\u653E\u5E73\u53F0\u5E94\u7528\u51ED\u8BC1 AppKey").addText(
      (text) => text.setPlaceholder("\u8BF7\u8F93\u5165 AppKey").setValue(this.plugin.settings.appKey).onChange(async (value) => {
        this.plugin.settings.appKey = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("AppSecret (Client Secret)").setDesc("\u5F00\u653E\u5E73\u53F0\u5E94\u7528\u5BC6\u94A5 AppSecret").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("\u8BF7\u8F93\u5165 AppSecret").setValue(this.plugin.settings.appSecret).onChange(async (value) => {
        this.plugin.settings.appSecret = value.trim();
        await this.plugin.saveSettings();
      });
    });
    let authCodeInput = "";
    new import_obsidian.Setting(containerEl).setName("\u83B7\u53D6\u6388\u6743\u5E76\u6362\u53D6 Token").setDesc(
      this.plugin.settings.accessToken ? "\u2705 \u5DF2\u6388\u6743\u7F51\u76D8\u8D26\u53F7" : "\u26A0\uFE0F \u5C1A\u672A\u7ED1\u5B9A\u767E\u5EA6\u7F51\u76D8"
    ).addButton(
      (btn) => btn.setButtonText("\u7B2C\u4E00\u6B65\uFF1A\u6253\u5F00\u6388\u6743\u7F51\u9875").onClick(() => {
        try {
          const url = this.plugin.oauth.getOAuthUrl();
          window.open(url);
          new import_obsidian.Notice("\u8BF7\u5728\u6D4F\u89C8\u5668\u5B8C\u6210\u6388\u6743\uFF0C\u5E76\u590D\u5236\u7F51\u9875\u4E2D\u7684\u6388\u6743\u7801\uFF01");
        } catch (err) {
          const msg = err instanceof Error ? err.message : "\u8BF7\u5148\u586B\u5199 AppKey";
          new import_obsidian.Notice(msg);
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u586B\u5165\u6388\u6743\u7801 (Authorization Code)").setDesc("\u5C06\u7F51\u9875\u4E2D\u83B7\u53D6\u7684 Code \u7C98\u8D34\u5728\u6B64\u5904\u6362\u53D6\u6301\u4E45\u51ED\u636E").addText(
      (text) => text.setPlaceholder("\u7C98\u8D34\u6388\u6743\u7801...").onChange((value) => {
        authCodeInput = value.trim();
      })
    ).addButton(
      (btn) => btn.setButtonText("\u7B2C\u4E8C\u6B65\uFF1A\u786E\u8BA4\u6362\u53D6 Token").setCta().onClick(async () => {
        if (!authCodeInput) {
          new import_obsidian.Notice("\u8BF7\u5148\u8F93\u5165\u7F51\u9875\u8FD4\u56DE\u7684\u6388\u6743\u7801");
          return;
        }
        try {
          btn.setDisabled(true);
          btn.setButtonText("\u6B63\u5728\u6362\u53D6...");
          await this.plugin.oauth.exchangeCodeForToken(authCodeInput);
          new import_obsidian.Notice("\u{1F389} \u767E\u5EA6\u7F51\u76D8\u8D26\u53F7\u7ED1\u5B9A\u6210\u529F\uFF01");
          this.display();
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          new import_obsidian.Notice(`\u7ED1\u5B9A\u5931\u8D25: ${msg}`);
        } finally {
          btn.setDisabled(false);
          btn.setButtonText("\u7B2C\u4E8C\u6B65\uFF1A\u786E\u8BA4\u6362\u53D6 Token");
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("2. \u5B58\u50A8\u4E0E\u76EE\u5F55\u89C4\u5212").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u7F51\u76D8\u7AEF\u6839\u76EE\u5F55").setDesc("\u7F51\u76D8\u4E2D\u5B58\u653E\u6B64\u77E5\u8BC6\u5E93\u7684\u7EDD\u5BF9\u8DEF\u5F84 (\u9ED8\u8BA4: /apps/obsidian_vault)").addText(
      (text) => text.setPlaceholder("/apps/obsidian_vault").setValue(this.plugin.settings.remoteBasePath).onChange(async (val) => {
        this.plugin.settings.remoteBasePath = val.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("3. \u914D\u7F6E\u540C\u6B65\u4E0E\u6587\u4EF6\u8FC7\u6EE4").setHeading();
    const configDirName = this.app.vault.configDir;
    new import_obsidian.Setting(containerEl).setName(`\u540C\u6B65 ${configDirName} \u914D\u7F6E\u76EE\u5F55`).setDesc(`\u5F00\u542F\u540E\u5C06\u540C\u6B65 ${configDirName} \u4E2D\u7684\u63D2\u4EF6\u3001\u5916\u89C2\u4E0E\u5168\u5C40\u914D\u7F6E\uFF08\u81EA\u52A8\u6392\u9664 workspace.json \u5E03\u5C40\u7F13\u5B58\uFF09`).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.syncObsidianConfig).onChange(async (val) => {
        this.plugin.settings.syncObsidianConfig = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(`\u540C\u6B65\u7B2C\u4E09\u65B9\u63D2\u4EF6 (${configDirName}/plugins)`).setDesc("\u5F00\u542F\u540E\u5C06\u5728\u591A\u7AEF\u540C\u6B65\u5DF2\u5B89\u88C5\u7684\u793E\u533A\u63D2\u4EF6").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.syncPlugins).onChange(async (val) => {
        this.plugin.settings.syncPlugins = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(`\u540C\u6B65\u5916\u89C2\u4E0E\u4E3B\u9898 (${configDirName}/themes)`).setDesc("\u5F00\u542F\u540E\u540C\u6B65\u5DF2\u4E0B\u8F7D\u7684\u4E3B\u9898\u4E0E CSS \u7247\u6BB5").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.syncThemes).onChange(async (val) => {
        this.plugin.settings.syncThemes = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6392\u9664\u89C4\u5219 (Ignored Patterns)").setDesc("\u6BCF\u884C\u4E00\u6761 Glob \u5339\u914D\u89C4\u5219\uFF0C\u5339\u914D\u7684\u6587\u4EF6\u5C06\u5B8C\u5168\u4E0D\u53C2\u4E0E\u540C\u6B65").addTextArea((area) => {
      area.inputEl.rows = 6;
      area.inputEl.addClass("baidu-sync-textarea");
      area.setValue(this.plugin.settings.ignoredPatterns).onChange(async (val) => {
        this.plugin.settings.ignoredPatterns = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("4. \u540C\u6B65\u89E6\u53D1\u673A\u5236").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u542F\u52A8\u65F6\u81EA\u52A8\u540C\u6B65").setDesc("\u6253\u5F00 Obsidian \u65F6\u81EA\u52A8\u5728\u540E\u53F0\u6267\u884C\u4E00\u6B21\u9759\u9ED8\u540C\u6B65").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.syncOnStartup).onChange(async (val) => {
        this.plugin.settings.syncOnStartup = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5B9A\u65F6\u81EA\u52A8\u540C\u6B65\u5468\u671F (\u5206\u949F)").setDesc("\u8BBE\u5B9A\u540E\u53F0\u5B9A\u65F6\u9759\u9ED8\u540C\u6B65\u7684\u65F6\u95F4\u95F4\u9694\uFF0C\u8BBE\u4E3A 0 \u5219\u7981\u7528\u5B9A\u65F6\u540C\u6B65").addText(
      (text) => text.setPlaceholder("10").setValue(String(this.plugin.settings.syncIntervalMinutes)).onChange(async (val) => {
        const num = parseInt(val, 10);
        this.plugin.settings.syncIntervalMinutes = isNaN(num) ? 0 : Math.max(0, num);
        await this.plugin.saveSettings();
        this.plugin.resetInterval();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u4FDD\u5B58/\u4FEE\u6539\u540E\u9632\u6296\u81EA\u52A8\u540C\u6B65").setDesc("\u6587\u4EF6\u4FDD\u5B58\u6216\u7F16\u8F91\u505C\u6B62\u4E00\u6BB5\u65F6\u95F4\u540E\u81EA\u52A8\u89E6\u53D1\u540C\u6B65").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.syncOnSave).onChange(async (val) => {
        this.plugin.settings.syncOnSave = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("5. \u4F20\u8F93\u8C03\u5EA6\u4E0E\u7F51\u7EDC\u5E76\u53D1").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u5E76\u53D1\u4F20\u8F93\u8BF7\u6C42\u6570 (1~5)").setDesc("\u540C\u65F6\u4E0A\u4F20/\u4E0B\u8F7D\u7684\u4EFB\u52A1\u6570\uFF0C\u63A8\u8350\u8BBE\u4E3A 2~3 \u907F\u514D\u89E6\u53D1\u767E\u5EA6\u7F51\u76D8 QPS \u9891\u7387\u9650\u5236").addSlider(
      (slider) => slider.setLimits(1, 5, 1).setValue(this.plugin.settings.concurrency).onChange(async (val) => {
        this.plugin.settings.concurrency = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("6. \u7AEF\u5230\u7AEF\u9690\u79C1\u52A0\u5BC6 (E2EE)").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u5F00\u542F AES-256-GCM \u7AEF\u5230\u7AEF\u52A0\u5BC6").setDesc("\u5F00\u542F\u540E\u6240\u6709\u6587\u4EF6\u5728\u4E0A\u4F20\u5230\u767E\u5EA6\u7F51\u76D8\u524D\u5747\u4F1A\u8FDB\u884C\u9AD8\u5F3A\u5EA6\u52A0\u5BC6\uFF0C\u7F51\u76D8\u7AEF\u65E0\u6CD5\u67E5\u770B\u660E\u6587\u3002\u6CE8\u610F\uFF1A\u591A\u7AEF\u540C\u6B65\u5FC5\u987B\u914D\u7F6E\u5B8C\u5168\u76F8\u540C\u7684\u5BC6\u7801\uFF01").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableE2EE).onChange(async (val) => {
        this.plugin.settings.enableE2EE = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("E2EE \u89E3\u5BC6\u4E0E\u52A0\u5BC6\u5BC6\u7801").setDesc("\u7528\u4E8E\u751F\u6210\u6D3E\u751F\u79D8\u94A5\u7684\u4E3B\u5BC6\u7801").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("\u8BF7\u8F93\u5165\u52A0\u5BC6\u5BC6\u7801").setValue(this.plugin.settings.e2eePassword).onChange(async (val) => {
        this.plugin.settings.e2eePassword = val;
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/baidu/oauth.ts
var import_obsidian2 = require("obsidian");
var BaiduOAuthManager = class {
  constructor(getSettings, saveSettings) {
    this.getSettings = getSettings;
    this.saveSettings = saveSettings;
  }
  getOAuthUrl() {
    const settings = this.getSettings();
    if (!settings.appKey) {
      throw new Error("\u8BF7\u5148\u586B\u5199 AppKey");
    }
    const clientId = encodeURIComponent(settings.appKey.trim());
    return `https://openapi.baidu.com/oauth/2.0/authorize?response_type=code&client_id=${clientId}&redirect_uri=oob&scope=basic,netdisk`;
  }
  async exchangeCodeForToken(code) {
    const settings = this.getSettings();
    if (!settings.appKey || !settings.appSecret) {
      throw new Error("\u8BF7\u5148\u586B\u5199 AppKey \u4E0E AppSecret");
    }
    const trimmedCode = code.trim();
    const url = "https://openapi.baidu.com/oauth/2.0/token";
    const body = new URLSearchParams({
      grant_type: "authorization_code",
      code: trimmedCode,
      client_id: settings.appKey.trim(),
      client_secret: settings.appSecret.trim(),
      redirect_uri: "oob"
    });
    const resp = await (0, import_obsidian2.requestUrl)({
      url,
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded"
      },
      body: body.toString()
    });
    if (resp.status !== 200) {
      throw new Error(`\u83B7\u53D6 Token \u5931\u8D25 (HTTP ${resp.status}): ${resp.text}`);
    }
    const tokenData = resp.json;
    if (tokenData.error) {
      throw new Error(`\u6388\u6743\u9519\u8BEF [${tokenData.error}]: ${tokenData.error_description || "\u672A\u77E5\u9519\u8BEF"}`);
    }
    const now = Date.now();
    const expiresInMs = (tokenData.expires_in || 2592e3) * 1e3;
    settings.accessToken = tokenData.access_token;
    settings.refreshToken = tokenData.refresh_token;
    settings.tokenExpiresAt = now + expiresInMs;
    await this.saveSettings(settings);
    return tokenData;
  }
  async refreshTokenIfNeeded(force = false) {
    const settings = this.getSettings();
    if (!settings.refreshToken) {
      throw new Error("\u5C1A\u672A\u6388\u6743\u767E\u5EA6\u7F51\u76D8\u8D26\u53F7\uFF0C\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u5B8C\u6210\u6388\u6743");
    }
    const now = Date.now();
    const shouldRefresh = force || !settings.tokenExpiresAt || settings.tokenExpiresAt - now < 24 * 3600 * 1e3;
    if (!shouldRefresh && settings.accessToken) {
      return settings.accessToken;
    }
    const url = "https://openapi.baidu.com/oauth/2.0/token";
    const body = new URLSearchParams({
      grant_type: "refresh_token",
      refresh_token: settings.refreshToken,
      client_id: settings.appKey.trim(),
      client_secret: settings.appSecret.trim()
    });
    try {
      const resp = await (0, import_obsidian2.requestUrl)({
        url,
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded"
        },
        body: body.toString()
      });
      if (resp.status !== 200) {
        throw new Error(`\u5237\u65B0 Token \u5931\u8D25 (HTTP ${resp.status}): ${resp.text}`);
      }
      const tokenData = resp.json;
      if (tokenData.error) {
        throw new Error(`\u5237\u65B0 Token \u5F02\u5E38 [${tokenData.error}]: ${tokenData.error_description || "\u672A\u77E5\u9519\u8BEF"}`);
      }
      settings.accessToken = tokenData.access_token;
      if (tokenData.refresh_token) {
        settings.refreshToken = tokenData.refresh_token;
      }
      settings.tokenExpiresAt = Date.now() + (tokenData.expires_in || 2592e3) * 1e3;
      await this.saveSettings(settings);
      return settings.accessToken;
    } catch (err) {
      console.error("[BaiduSync] \u5237\u65B0 Token \u5931\u8D25:", err);
      throw err instanceof Error ? err : new Error(String(err));
    }
  }
  async getUserInfo() {
    const token = await this.refreshTokenIfNeeded();
    const url = `https://pan.baidu.com/rest/2.0/xpan/nas?method=uinfo&access_token=${token}`;
    const resp = await (0, import_obsidian2.requestUrl)({
      url,
      method: "GET"
    });
    if (resp.status !== 200) {
      throw new Error(`\u83B7\u53D6\u7528\u6237\u4FE1\u606F\u5931\u8D25: HTTP ${resp.status}`);
    }
    return resp.json;
  }
};

// src/baidu/client.ts
var import_obsidian3 = require("obsidian");

// src/baidu/multipart.ts
function buildMultipartFormData(fileBuffer, fieldName = "file", fileName = "blob") {
  const boundary = "----BaiduSyncBoundary" + Math.random().toString(36).substring(2) + Date.now().toString(36);
  const encoder = new TextEncoder();
  const head = `--${boundary}\r
Content-Disposition: form-data; name="${fieldName}"; filename="${fileName}"\r
Content-Type: application/octet-stream\r
\r
`;
  const tail = `\r
--${boundary}--\r
`;
  const headBytes = encoder.encode(head);
  const tailBytes = encoder.encode(tail);
  const fileBytes = new Uint8Array(fileBuffer);
  const totalLength = headBytes.length + fileBytes.length + tailBytes.length;
  const result = new Uint8Array(totalLength);
  let offset = 0;
  result.set(headBytes, offset);
  offset += headBytes.length;
  result.set(fileBytes, offset);
  offset += fileBytes.length;
  result.set(tailBytes, offset);
  return {
    body: result.buffer,
    contentType: `multipart/form-data; boundary=${boundary}`
  };
}

// src/baidu/client.ts
var BaiduClient = class {
  constructor(oauth) {
    this.oauth = oauth;
  }
  async requestWithRetry(param, maxRetries = 3, initialDelayMs = 1e3) {
    let lastError = null;
    let delay = initialDelayMs;
    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      try {
        const resp = await (0, import_obsidian3.requestUrl)(param);
        if (resp.status === 200) {
          try {
            const data = resp.json;
            if (data && typeof data === "object") {
              if (data.errno === 31034) {
                throw new Error("Baidu Rate Limit Hit (errno: 31034)");
              }
              if (data.errno === -6) {
                console.warn("[BaiduSync] Token \u5931\u6548\uFF0C\u5C1D\u8BD5\u5237\u65B0\u5E76\u91CD\u8BD5...");
                await this.oauth.refreshTokenIfNeeded(true);
                throw new Error("Token expired (errno: -6)");
              }
            }
          } catch (e) {
            if (e instanceof Error && (e.message.includes("Rate Limit") || e.message.includes("Token expired"))) {
              throw e;
            }
          }
          return resp;
        }
        if (resp.status === 429 || resp.status >= 500) {
          throw new Error(`Server Error HTTP ${resp.status}`);
        }
        return resp;
      } catch (err) {
        lastError = err;
        if (attempt < maxRetries) {
          const jitter = Math.random() * 300;
          await new Promise((r) => window.setTimeout(r, delay + jitter));
          delay *= 2;
        }
      }
    }
    throw lastError instanceof Error ? lastError : new Error(String(lastError));
  }
  async listAll(rootPath) {
    const token = await this.oauth.refreshTokenIfNeeded();
    const cleanPath = rootPath.endsWith("/") ? rootPath.slice(0, -1) : rootPath;
    const allFiles = [];
    const dirQueue = [cleanPath];
    while (dirQueue.length > 0) {
      const currentDir = dirQueue.shift();
      let start = 0;
      const limit = 1e3;
      let hasMore = true;
      while (hasMore) {
        const url = `https://pan.baidu.com/rest/2.0/xpan/file?method=list&dir=${encodeURIComponent(
          currentDir
        )}&order=name&desc=0&start=${start}&limit=${limit}&web=web&folder=0&access_token=${token}`;
        const resp = await this.requestWithRetry({
          url,
          method: "GET"
        });
        if (resp.status !== 200) {
          throw new Error(`\u83B7\u53D6\u7F51\u76D8\u6587\u4EF6\u5217\u8868\u5931\u8D25: HTTP ${resp.status}`);
        }
        const data = resp.json;
        if (data.errno === -9 || data.errno === 31066 || data.errno === 20020) {
          hasMore = false;
          break;
        }
        if (data.errno !== 0 && data.errno !== void 0) {
          throw new Error(`\u83B7\u53D6\u7F51\u76D8\u5217\u8868\u8FD4\u56DE\u5F02\u5E38 (errno: ${data.errno})`);
        }
        if (data.list && Array.isArray(data.list)) {
          for (const item of data.list) {
            if (item.isdir === 1) {
              dirQueue.push(item.path);
            } else {
              allFiles.push(item);
            }
          }
          if (data.list.length < limit) {
            hasMore = false;
          } else {
            start += limit;
          }
        } else {
          hasMore = false;
        }
      }
    }
    return allFiles;
  }
  async getFileMeta(fsId) {
    const token = await this.oauth.refreshTokenIfNeeded();
    const url = `https://pan.baidu.com/rest/2.0/xpan/multimedia?method=filemetas&fsids=[${fsId}]&dlink=1&access_token=${token}`;
    const resp = await this.requestWithRetry({
      url,
      method: "GET"
    });
    if (resp.status !== 200) {
      throw new Error(`\u83B7\u53D6\u6587\u4EF6\u5143\u6570\u636E\u5931\u8D25: HTTP ${resp.status}`);
    }
    const data = resp.json;
    if (!data.list || data.list.length === 0) {
      throw new Error(`\u672A\u627E\u5230\u6587\u4EF6\u5143\u6570\u636E fsId=${fsId}`);
    }
    return data.list[0];
  }
  async downloadFile(dlink) {
    const token = await this.oauth.refreshTokenIfNeeded();
    const connector = dlink.includes("?") ? "&" : "?";
    const finalUrl = `${dlink}${connector}access_token=${token}`;
    const resp = await this.requestWithRetry({
      url: finalUrl,
      method: "GET",
      headers: {
        "User-Agent": "pan.baidu.com"
      }
    });
    if (resp.status !== 200) {
      throw new Error(`\u4E0B\u8F7D\u6587\u4EF6\u5931\u8D25: HTTP ${resp.status}`);
    }
    return resp.arrayBuffer;
  }
  async precreate(remotePath, size, blockList) {
    const token = await this.oauth.refreshTokenIfNeeded();
    const url = `https://pan.baidu.com/rest/2.0/xpan/file?method=precreate&access_token=${token}`;
    const body = new URLSearchParams({
      path: remotePath,
      size: size.toString(),
      isdir: "0",
      autoinit: "1",
      rtype: "3",
      // overwrite existing
      block_list: JSON.stringify(blockList)
    });
    const resp = await this.requestWithRetry({
      url,
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded"
      },
      body: body.toString()
    });
    if (resp.status !== 200) {
      throw new Error(`Precreate \u5931\u8D25 (HTTP ${resp.status}): ${resp.text}`);
    }
    const data = resp.json;
    if (data.errno !== 0) {
      throw new Error(`Precreate \u9519\u8BEF [errno: ${data.errno}]: ${resp.text}`);
    }
    return data;
  }
  async uploadSlice(remotePath, uploadid, partseq, sliceBuffer) {
    const token = await this.oauth.refreshTokenIfNeeded();
    const url = `https://d.pcs.baidu.com/rest/2.0/pcs/superfile2?method=upload&type=tmpfile&uploadid=${encodeURIComponent(
      uploadid
    )}&partseq=${partseq}&path=${encodeURIComponent(remotePath)}&access_token=${token}`;
    const { body, contentType } = buildMultipartFormData(sliceBuffer, "file", "blob");
    const resp = await this.requestWithRetry({
      url,
      method: "POST",
      headers: {
        "Content-Type": contentType
      },
      body
    });
    if (resp.status !== 200) {
      throw new Error(`\u5206\u7247\u4E0A\u4F20\u5931\u8D25 partseq=${partseq} (HTTP ${resp.status}): ${resp.text}`);
    }
  }
  async createFile(remotePath, size, uploadid, blockList) {
    const token = await this.oauth.refreshTokenIfNeeded();
    const url = `https://pan.baidu.com/rest/2.0/xpan/file?method=create&access_token=${token}`;
    const body = new URLSearchParams({
      path: remotePath,
      size: size.toString(),
      isdir: "0",
      rtype: "3",
      uploadid,
      block_list: JSON.stringify(blockList)
    });
    const resp = await this.requestWithRetry({
      url,
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded"
      },
      body: body.toString()
    });
    if (resp.status !== 200) {
      throw new Error(`\u5408\u5E76\u521B\u5EFA\u6587\u4EF6\u5931\u8D25 (HTTP ${resp.status}): ${resp.text}`);
    }
    const data = resp.json;
    if (data.errno !== 0) {
      throw new Error(`\u843D\u76D8\u521B\u5EFA\u6587\u4EF6\u9519\u8BEF [errno: ${data.errno}]: ${resp.text}`);
    }
    return data;
  }
  async createDirectory(remotePath) {
    const token = await this.oauth.refreshTokenIfNeeded();
    const url = `https://pan.baidu.com/rest/2.0/xpan/file?method=create&access_token=${token}`;
    const body = new URLSearchParams({
      path: remotePath,
      size: "0",
      isdir: "1",
      rtype: "0"
    });
    const resp = await this.requestWithRetry({
      url,
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded"
      },
      body: body.toString()
    });
    const data = resp.json;
    if (data.errno !== 0 && data.errno !== -8) {
      console.warn(`\u521B\u5EFA\u76EE\u5F55\u8B66\u544A path=${remotePath} errno=${data.errno}`);
    }
  }
  async deleteFiles(remotePaths) {
    if (remotePaths.length === 0) return;
    const token = await this.oauth.refreshTokenIfNeeded();
    const url = `https://pan.baidu.com/rest/2.0/xpan/file?method=filemanager&opera=delete&access_token=${token}`;
    const body = new URLSearchParams({
      filelist: JSON.stringify(remotePaths)
    });
    const resp = await this.requestWithRetry({
      url,
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded"
      },
      body: body.toString()
    });
    if (resp.status !== 200) {
      throw new Error(`\u5220\u9664\u7F51\u76D8\u6587\u4EF6\u5931\u8D25 (HTTP ${resp.status}): ${resp.text}`);
    }
    const data = resp.json;
    if (data.errno !== 0) {
      throw new Error(`\u5220\u9664\u7F51\u76D8\u6587\u4EF6\u9519\u8BEF [errno: ${data.errno}]: ${resp.text}`);
    }
  }
};

// src/sync/manifest.ts
var ManifestManager = class {
  constructor(adapter, manifestFilePath) {
    this.adapter = adapter;
    this.manifestFilePath = manifestFilePath;
    this.manifest = {
      version: 1,
      lastSyncTime: 0,
      files: {}
    };
  }
  async load() {
    try {
      if (await this.adapter.exists(this.manifestFilePath)) {
        const raw = await this.adapter.read(this.manifestFilePath);
        this.manifest = JSON.parse(raw);
        if (!this.manifest.files) {
          this.manifest.files = {};
        }
      }
    } catch (err) {
      console.warn("[BaiduSync] \u52A0\u8F7D sync_manifest \u5931\u8D25\uFF0C\u5C06\u4F7F\u7528\u7A7A\u6E05\u5355:", err);
      this.manifest = {
        version: 1,
        lastSyncTime: 0,
        files: {}
      };
    }
    return this.manifest;
  }
  async save() {
    try {
      const lastSlash = this.manifestFilePath.lastIndexOf("/");
      if (lastSlash > 0) {
        const dir = this.manifestFilePath.substring(0, lastSlash);
        if (!await this.adapter.exists(dir)) {
          await this.adapter.mkdir(dir);
        }
      }
      await this.adapter.write(
        this.manifestFilePath,
        JSON.stringify(this.manifest, null, 2)
      );
    } catch (err) {
      console.error("[BaiduSync] \u4FDD\u5B58 sync_manifest \u5931\u8D25:", err);
    }
  }
  get(path) {
    return this.manifest.files[path];
  }
  set(item) {
    this.manifest.files[item.path] = item;
  }
  delete(path) {
    delete this.manifest.files[path];
  }
  getAll() {
    return this.manifest.files;
  }
  updateLastSyncTime(time = Date.now()) {
    this.manifest.lastSyncTime = time;
  }
  getLastSyncTime() {
    return this.manifest.lastSyncTime;
  }
};

// src/sync/engine.ts
var import_obsidian4 = require("obsidian");

// src/crypto/md5.ts
function safeAdd(x, y) {
  const lsw = (x & 65535) + (y & 65535);
  const msw = (x >> 16) + (y >> 16) + (lsw >> 16);
  return msw << 16 | lsw & 65535;
}
function bitRotateLeft(num, cnt) {
  return num << cnt | num >>> 32 - cnt;
}
function md5cmn(q, a, b, x, s, t) {
  return safeAdd(bitRotateLeft(safeAdd(safeAdd(a, q), safeAdd(x, t)), s), b);
}
function md5ff(a, b, c, d, x, s, t) {
  return md5cmn(b & c | ~b & d, a, b, x, s, t);
}
function md5gg(a, b, c, d, x, s, t) {
  return md5cmn(b & d | c & ~d, a, b, x, s, t);
}
function md5hh(a, b, c, d, x, s, t) {
  return md5cmn(b ^ c ^ d, a, b, x, s, t);
}
function md5ii(a, b, c, d, x, s, t) {
  return md5cmn(c ^ (b | ~d), a, b, x, s, t);
}
function md5(buffer) {
  const bytes = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
  const nBytes = bytes.length;
  const nWords = ((nBytes + 8 >>> 6) + 1) * 16;
  const words = new Int32Array(nWords);
  for (let i = 0; i < nBytes; i++) {
    words[i >>> 2] |= bytes[i] << i % 4 * 8;
  }
  words[nBytes >>> 2] |= 128 << nBytes % 4 * 8;
  words[nWords - 2] = nBytes * 8 & 4294967295;
  words[nWords - 1] = Math.floor(nBytes * 8 / 4294967296);
  let a = 1732584193;
  let b = -271733879;
  let c = -1732584194;
  let d = 271733878;
  for (let i = 0; i < nWords; i += 16) {
    const olda = a;
    const oldb = b;
    const oldc = c;
    const oldd = d;
    a = md5ff(a, b, c, d, words[i], 7, -680876936);
    d = md5ff(d, a, b, c, words[i + 1], 12, -389564586);
    c = md5ff(c, d, a, b, words[i + 2], 17, 606105819);
    b = md5ff(b, c, d, a, words[i + 3], 22, -1044525330);
    a = md5ff(a, b, c, d, words[i + 4], 7, -176418897);
    d = md5ff(d, a, b, c, words[i + 5], 12, 1200080426);
    c = md5ff(c, d, a, b, words[i + 6], 17, -1473231341);
    b = md5ff(b, c, d, a, words[i + 7], 22, -45705983);
    a = md5ff(a, b, c, d, words[i + 8], 7, 1770035416);
    d = md5ff(d, a, b, c, words[i + 9], 12, -1958414417);
    c = md5ff(c, d, a, b, words[i + 10], 17, -42063);
    b = md5ff(b, c, d, a, words[i + 11], 22, -1990404162);
    a = md5ff(a, b, c, d, words[i + 12], 7, 1804603682);
    d = md5ff(d, a, b, c, words[i + 13], 12, -40341101);
    c = md5ff(c, d, a, b, words[i + 14], 17, -1502002290);
    b = md5ff(b, c, d, a, words[i + 15], 22, 1236535329);
    a = md5gg(a, b, c, d, words[i + 1], 5, -165796510);
    d = md5gg(d, a, b, c, words[i + 6], 9, -1069501632);
    c = md5gg(c, d, a, b, words[i + 11], 14, 643717713);
    b = md5gg(b, c, d, a, words[i], 20, -373897302);
    a = md5gg(a, b, c, d, words[i + 5], 5, -701558691);
    d = md5gg(d, a, b, c, words[i + 10], 9, 38016083);
    c = md5gg(c, d, a, b, words[i + 15], 14, -660478335);
    b = md5gg(b, c, d, a, words[i + 4], 20, -405537848);
    a = md5gg(a, b, c, d, words[i + 9], 5, 568446438);
    d = md5gg(d, a, b, c, words[i + 14], 9, -1019803690);
    c = md5gg(c, d, a, b, words[i + 3], 14, -187363961);
    b = md5gg(b, c, d, a, words[i + 8], 20, 1163531501);
    a = md5gg(a, b, c, d, words[i + 13], 5, -1444681467);
    d = md5gg(d, a, b, c, words[i + 2], 9, -51403784);
    c = md5gg(c, d, a, b, words[i + 7], 14, 1735328473);
    b = md5gg(b, c, d, a, words[i + 12], 20, -1926607734);
    a = md5hh(a, b, c, d, words[i + 5], 4, -378558);
    d = md5hh(d, a, b, c, words[i + 8], 11, -2022574463);
    c = md5hh(c, d, a, b, words[i + 11], 16, 1839030562);
    b = md5hh(b, c, d, a, words[i + 14], 23, -35309556);
    a = md5hh(a, b, c, d, words[i + 1], 4, -1530992060);
    d = md5hh(d, a, b, c, words[i + 4], 11, 1272893353);
    c = md5hh(c, d, a, b, words[i + 7], 16, -155497632);
    b = md5hh(b, c, d, a, words[i + 10], 23, -1094730640);
    a = md5hh(a, b, c, d, words[i + 13], 4, 681279174);
    d = md5hh(d, a, b, c, words[i], 11, -358537222);
    c = md5hh(c, d, a, b, words[i + 3], 16, -722521979);
    b = md5hh(b, c, d, a, words[i + 6], 23, 76029189);
    a = md5hh(a, b, c, d, words[i + 9], 4, -640364487);
    d = md5hh(d, a, b, c, words[i + 12], 11, -421815835);
    c = md5hh(c, d, a, b, words[i + 15], 16, 530742520);
    b = md5hh(b, c, d, a, words[i + 2], 23, -995338651);
    a = md5ii(a, b, c, d, words[i], 6, -198630844);
    d = md5ii(d, a, b, c, words[i + 7], 10, 1126891415);
    c = md5ii(c, d, a, b, words[i + 14], 15, -1416354905);
    b = md5ii(b, c, d, a, words[i + 5], 21, -57434055);
    a = md5ii(a, b, c, d, words[i + 12], 6, 1700485571);
    d = md5ii(d, a, b, c, words[i + 3], 10, -1894986606);
    c = md5ii(c, d, a, b, words[i + 10], 15, -1051523);
    b = md5ii(b, c, d, a, words[i + 1], 21, -2054922799);
    a = md5ii(a, b, c, d, words[i + 8], 6, 1873313359);
    d = md5ii(d, a, b, c, words[i + 15], 10, -30611744);
    c = md5ii(c, d, a, b, words[i + 6], 15, -1560198380);
    b = md5ii(b, c, d, a, words[i + 13], 21, 1309151649);
    a = md5ii(a, b, c, d, words[i + 4], 6, -145523070);
    d = md5ii(d, a, b, c, words[i + 11], 10, -1120210379);
    c = md5ii(c, d, a, b, words[i + 2], 15, 718787259);
    b = md5ii(b, c, d, a, words[i + 9], 21, -343485551);
    a = safeAdd(a, olda);
    b = safeAdd(b, oldb);
    c = safeAdd(c, oldc);
    d = safeAdd(d, oldd);
  }
  const hexDigits = "0123456789abcdef";
  let result = "";
  const arr = [a, b, c, d];
  for (let i = 0; i < 4; i++) {
    for (let j = 0; j < 4; j++) {
      const byte = arr[i] >>> j * 8 & 255;
      result += hexDigits.charAt(byte >>> 4 & 15) + hexDigits.charAt(byte & 15);
    }
  }
  return result;
}

// src/crypto/e2ee.ts
var MAGIC_HEADER = new Uint8Array([66, 68, 83, 89, 78, 67, 95, 69, 50, 69, 69, 1]);
var PBKDF2_ITERATIONS = 1e5;
function isEncrypted(buffer) {
  if (buffer.byteLength < MAGIC_HEADER.length + 16 + 12 + 16) {
    return false;
  }
  const view = new Uint8Array(buffer, 0, MAGIC_HEADER.length);
  for (let i = 0; i < MAGIC_HEADER.length; i++) {
    if (view[i] !== MAGIC_HEADER[i]) {
      return false;
    }
  }
  return true;
}
async function deriveKey(password, salt) {
  const enc = new TextEncoder();
  const keyMaterial = await window.crypto.subtle.importKey(
    "raw",
    enc.encode(password),
    { name: "PBKDF2" },
    false,
    ["deriveKey"]
  );
  return window.crypto.subtle.deriveKey(
    {
      name: "PBKDF2",
      salt,
      iterations: PBKDF2_ITERATIONS,
      hash: "SHA-256"
    },
    keyMaterial,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"]
  );
}
async function encryptData(data, password) {
  const salt = window.crypto.getRandomValues(new Uint8Array(16));
  const iv = window.crypto.getRandomValues(new Uint8Array(12));
  const key = await deriveKey(password, salt);
  const ciphertext = await window.crypto.subtle.encrypt(
    {
      name: "AES-GCM",
      iv
    },
    key,
    data
  );
  const totalLength = MAGIC_HEADER.length + salt.length + iv.length + ciphertext.byteLength;
  const result = new Uint8Array(totalLength);
  let offset = 0;
  result.set(MAGIC_HEADER, offset);
  offset += MAGIC_HEADER.length;
  result.set(salt, offset);
  offset += salt.length;
  result.set(iv, offset);
  offset += iv.length;
  result.set(new Uint8Array(ciphertext), offset);
  return result.buffer;
}
async function decryptData(encryptedBuffer, password) {
  if (!isEncrypted(encryptedBuffer)) {
    return encryptedBuffer;
  }
  let offset = MAGIC_HEADER.length;
  const salt = new Uint8Array(encryptedBuffer, offset, 16);
  offset += 16;
  const iv = new Uint8Array(encryptedBuffer, offset, 12);
  offset += 12;
  const ciphertext = encryptedBuffer.slice(offset);
  const key = await deriveKey(password, salt);
  try {
    return await window.crypto.subtle.decrypt(
      {
        name: "AES-GCM",
        iv
      },
      key,
      ciphertext
    );
  } catch {
    throw new Error("E2EE \u89E3\u5BC6\u5931\u8D25\uFF1A\u5BC6\u7801\u9519\u8BEF\u6216\u6587\u4EF6\u635F\u574F");
  }
}

// src/baidu/uploader.ts
var CHUNK_SIZE = 4 * 1024 * 1024;
var BaiduUploader = class {
  constructor(client) {
    this.client = client;
  }
  async uploadFile(remotePath, fileBuffer, options = {}) {
    let payload = fileBuffer;
    if (options.enableE2EE && options.e2eePassword) {
      payload = await encryptData(payload, options.e2eePassword);
    }
    const totalSize = payload.byteLength;
    const totalParts = Math.max(1, Math.ceil(totalSize / CHUNK_SIZE));
    const blockList = [];
    for (let i = 0; i < totalParts; i++) {
      const start = i * CHUNK_SIZE;
      const end = Math.min(start + CHUNK_SIZE, totalSize);
      const slice = payload.slice(start, end);
      const partMd5 = md5(slice);
      blockList.push(partMd5);
    }
    const precreateRes = await this.client.precreate(remotePath, totalSize, blockList);
    const uploadId = precreateRes.uploadid;
    const neededParts = precreateRes.block_list && Array.isArray(precreateRes.block_list) ? precreateRes.block_list : [];
    for (let idx = 0; idx < neededParts.length; idx++) {
      const partseq = neededParts[idx];
      const start = partseq * CHUNK_SIZE;
      const end = Math.min(start + CHUNK_SIZE, totalSize);
      const slice = payload.slice(start, end);
      await this.client.uploadSlice(remotePath, uploadId, partseq, slice);
      options.onProgress?.(idx + 1, neededParts.length);
    }
    const commitRes = await this.client.createFile(remotePath, totalSize, uploadId, blockList);
    return commitRes;
  }
};

// src/baidu/downloader.ts
var BaiduDownloader = class {
  constructor(client) {
    this.client = client;
  }
  async downloadByFsId(fsId, options = {}) {
    const meta = await this.client.getFileMeta(fsId);
    if (!meta.dlink) {
      throw new Error(`\u6587\u4EF6\u5143\u6570\u636E\u4E2D\u7F3A\u5C11 dlink (fsId: ${fsId})`);
    }
    const rawBuffer = await this.client.downloadFile(meta.dlink);
    if (isEncrypted(rawBuffer)) {
      if (!options.e2eePassword) {
        throw new Error("\u68C0\u6D4B\u5230\u8BE5\u6587\u4EF6\u5DF2\u4F7F\u7528 E2EE \u7AEF\u5230\u7AEF\u52A0\u5BC6\uFF0C\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E\u89E3\u5BC6\u5BC6\u7801");
      }
      return await decryptData(rawBuffer, options.e2eePassword);
    }
    return rawBuffer;
  }
};

// src/sync/filter.ts
function globToRegex(glob) {
  const clean = glob.trim();
  let regexStr = "^";
  let i = 0;
  while (i < clean.length) {
    const c = clean[i];
    if (c === "*" && clean[i + 1] === "*") {
      regexStr += ".*";
      i += 2;
      if (clean[i] === "/") {
        i++;
      }
    } else if (c === "*") {
      regexStr += "[^/]*";
      i++;
    } else if (c === "?") {
      regexStr += "[^/]";
      i++;
    } else if (".+^$()|{}[]\\".includes(c)) {
      regexStr += "\\" + c;
      i++;
    } else {
      regexStr += c;
      i++;
    }
  }
  regexStr += "$";
  return new RegExp(regexStr);
}
var SyncFilter = class {
  constructor(settings, configDir = "") {
    this.settings = settings;
    this.configDir = configDir;
    this.compiledPatterns = [];
    this.recompilePatterns();
  }
  updateSettings(settings) {
    this.settings = settings;
    this.recompilePatterns();
  }
  recompilePatterns() {
    this.compiledPatterns = [];
    const lines = this.settings.ignoredPatterns.split("\n");
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith("#")) {
        try {
          this.compiledPatterns.push(globToRegex(trimmed));
        } catch {
        }
      }
    }
  }
  shouldIgnore(relativePath) {
    const normalized = relativePath.replace(/\\/g, "/");
    if (normalized.includes("baidu-netdisk-sync") || normalized.includes("obsidian-baidu-netdisk-sync") || normalized.endsWith("sync_manifest.json")) {
      return true;
    }
    if (normalized.startsWith(".trash/") || normalized === ".trash") {
      return true;
    }
    if (normalized.startsWith(".git/") || normalized.includes("/.git/")) {
      return true;
    }
    const configPrefix = this.configDir ? `${this.configDir}/` : "";
    if (configPrefix && normalized.startsWith(configPrefix)) {
      if (!this.settings.syncObsidianConfig) {
        return true;
      }
      if (normalized.includes("/workspace.json") || normalized.includes("/workspace-mobile.json") || normalized.endsWith("/workspace.json") || normalized.endsWith("/workspace-mobile.json") || normalized.includes("/cache/") || normalized.includes("/indexeddb/")) {
        return true;
      }
      if (!this.settings.syncPlugins && normalized.includes("/plugins/")) {
        return true;
      }
      if (!this.settings.syncThemes && normalized.includes("/themes/")) {
        return true;
      }
    }
    for (const pattern of this.compiledPatterns) {
      if (pattern.test(normalized)) {
        return true;
      }
    }
    return false;
  }
};

// src/sync/queue.ts
var AsyncQueue = class {
  constructor(concurrency = 3) {
    this.concurrency = concurrency;
    this.activeCount = 0;
    this.queue = [];
  }
  setConcurrency(concurrency) {
    this.concurrency = Math.max(1, concurrency);
  }
  add(task) {
    return new Promise((resolve, reject) => {
      const runner = async () => {
        try {
          const res = await task();
          resolve(res);
        } catch (err) {
          reject(err instanceof Error ? err : new Error(String(err)));
        } finally {
          this.activeCount--;
          this.next();
        }
      };
      this.queue.push(runner);
      this.next();
    });
  }
  next() {
    while (this.activeCount < this.concurrency && this.queue.length > 0) {
      const task = this.queue.shift();
      if (task) {
        this.activeCount++;
        void task();
      }
    }
  }
  async waitAll() {
    while (this.activeCount > 0 || this.queue.length > 0) {
      await new Promise((r) => window.setTimeout(r, 50));
    }
  }
};

// src/sync/planner.ts
var SyncPlanner = class {
  static plan(localFiles, remoteFiles, manifestFiles, remoteBasePath) {
    const plans = [];
    const allPaths = /* @__PURE__ */ new Set([
      ...localFiles.keys(),
      ...remoteFiles.keys(),
      ...Object.keys(manifestFiles)
    ]);
    const normalizeRemoteBase = remoteBasePath.endsWith("/") ? remoteBasePath.slice(0, -1) : remoteBasePath;
    for (const path of allPaths) {
      const local = localFiles.get(path);
      const remote = remoteFiles.get(path);
      const manifest = manifestFiles[path];
      const remotePath = remote?.remotePath || `${normalizeRemoteBase}/${path}`;
      if (local && remote) {
        if (!manifest) {
          if (local.mtime >= remote.mtime) {
            plans.push({
              path,
              remotePath,
              action: "UPLOAD",
              reason: "\u53CC\u7AEF\u5747\u5B58\u5728\u4E14\u65E0\u540C\u6B65\u5386\u53F2\uFF0C\u672C\u5730\u65F6\u95F4\u6233\u8F83\u65B0 (LWW \u80DC\u51FA)",
              local,
              remote
            });
          } else {
            plans.push({
              path,
              remotePath,
              action: "DOWNLOAD",
              reason: "\u53CC\u7AEF\u5747\u5B58\u5728\u4E14\u65E0\u540C\u6B65\u5386\u53F2\uFF0C\u8FDC\u7AEF\u65F6\u95F4\u6233\u8F83\u65B0 (LWW \u80DC\u51FA)",
              local,
              remote
            });
          }
          continue;
        }
        const localChanged = Math.abs(local.mtime - manifest.mtime) > 1e3 || local.size !== manifest.size;
        const expectedRemoteSize = manifest.remoteSize !== void 0 ? manifest.remoteSize : manifest.size;
        const remoteChanged = Math.abs(remote.mtime - manifest.remoteMtime) > 1e3 || remote.size !== expectedRemoteSize;
        if (!localChanged && !remoteChanged) {
          continue;
        } else if (localChanged && !remoteChanged) {
          plans.push({
            path,
            remotePath,
            action: "UPLOAD",
            reason: "\u672C\u5730\u6587\u4EF6\u6709\u66F4\u65B0\uFF0C\u63A8\u9001\u5230\u7F51\u76D8",
            local,
            remote,
            manifest
          });
        } else if (!localChanged && remoteChanged) {
          plans.push({
            path,
            remotePath,
            action: "DOWNLOAD",
            reason: "\u7F51\u76D8\u7AEF\u6587\u4EF6\u6709\u66F4\u65B0\uFF0C\u62C9\u53D6\u5230\u672C\u5730",
            local,
            remote,
            manifest
          });
        } else {
          if (local.mtime >= remote.mtime) {
            plans.push({
              path,
              remotePath,
              action: "UPLOAD",
              reason: "\u53CC\u7AEF\u5E76\u53D1\u4FEE\u6539\u4EA7\u751F\u51B2\u7A81\uFF0C\u672C\u5730\u65F6\u95F4\u6233\u8F83\u65B0 (LWW \u8986\u76D6\u8FDC\u7AEF)",
              local,
              remote,
              manifest
            });
          } else {
            plans.push({
              path,
              remotePath,
              action: "DOWNLOAD",
              reason: "\u53CC\u7AEF\u5E76\u53D1\u4FEE\u6539\u4EA7\u751F\u51B2\u7A81\uFF0C\u8FDC\u7AEF\u65F6\u95F4\u6233\u8F83\u65B0 (LWW \u8986\u76D6\u672C\u5730)",
              local,
              remote,
              manifest
            });
          }
        }
        continue;
      }
      if (local && !remote) {
        if (!manifest) {
          plans.push({
            path,
            remotePath,
            action: "UPLOAD",
            reason: "\u672C\u5730\u65B0\u589E\u6587\u4EF6\uFF0C\u63A8\u9001\u5230\u7F51\u76D8",
            local
          });
        } else {
          const localChanged = Math.abs(local.mtime - manifest.mtime) > 1e3 || local.size !== manifest.size;
          if (localChanged) {
            plans.push({
              path,
              remotePath,
              action: "UPLOAD",
              reason: "\u8FDC\u7AEF\u5DF2\u5220\u9664\u4F46\u672C\u5730\u6709\u65B0\u4FEE\u6539\uFF0C\u91CD\u65B0\u63A8\u9001\u5230\u7F51\u76D8",
              local,
              manifest
            });
          } else {
            plans.push({
              path,
              remotePath,
              action: "DELETE_LOCAL",
              reason: "\u7F51\u76D8\u7AEF\u5DF2\u5220\u9664\uFF0C\u540C\u6B65\u79FB\u5165\u672C\u5730\u56DE\u6536\u7AD9",
              local,
              manifest
            });
          }
        }
        continue;
      }
      if (!local && remote) {
        if (!manifest) {
          plans.push({
            path,
            remotePath,
            action: "DOWNLOAD",
            reason: "\u7F51\u76D8\u7AEF\u65B0\u589E\u6587\u4EF6\uFF0C\u62C9\u53D6\u5230\u672C\u5730",
            remote
          });
        } else {
          const expectedRemoteSize = manifest.remoteSize !== void 0 ? manifest.remoteSize : manifest.size;
          const remoteChanged = Math.abs(remote.mtime - manifest.remoteMtime) > 1e3 || remote.size !== expectedRemoteSize;
          if (remoteChanged) {
            plans.push({
              path,
              remotePath,
              action: "DOWNLOAD",
              reason: "\u672C\u5730\u5DF2\u5220\u9664\u4F46\u7F51\u76D8\u7AEF\u6709\u65B0\u4FEE\u6539\uFF0C\u91CD\u65B0\u62C9\u53D6\u5230\u672C\u5730",
              remote,
              manifest
            });
          } else {
            plans.push({
              path,
              remotePath,
              action: "DELETE_REMOTE",
              reason: "\u672C\u5730\u5DF2\u5220\u9664\uFF0C\u540C\u6B65\u79FB\u5165\u7F51\u76D8\u56DE\u6536\u7AD9",
              remote,
              manifest
            });
          }
        }
        continue;
      }
      if (!local && !remote && manifest) {
        plans.push({
          path,
          remotePath,
          action: "CLEAN_MANIFEST",
          reason: "\u4E24\u7AEF\u5747\u5DF2\u4E0D\u5B58\u5728\uFF0C\u6E05\u7406\u5143\u6570\u636E\u57FA\u7EBF",
          manifest
        });
      }
    }
    return plans;
  }
};

// src/sync/engine.ts
var SyncEngine = class {
  constructor(app, getSettings, saveSettings, client, manifest) {
    this.app = app;
    this.getSettings = getSettings;
    this.saveSettings = saveSettings;
    this.client = client;
    this.manifest = manifest;
    this.state = "idle";
    this.logs = [];
    this.onStateChangeListeners = [];
    const settings = this.getSettings();
    this.filter = new SyncFilter(settings, this.app.vault.configDir);
    this.queue = new AsyncQueue(settings.concurrency || 3);
    this.uploader = new BaiduUploader(this.client);
    this.downloader = new BaiduDownloader(this.client);
  }
  onStateChange(listener) {
    this.onStateChangeListeners.push(listener);
  }
  setState(state, message) {
    this.state = state;
    for (const listener of this.onStateChangeListeners) {
      listener(state, message);
    }
  }
  getState() {
    return this.state;
  }
  isSyncing() {
    return this.state !== "idle" && this.state !== "error";
  }
  getLogs() {
    return [...this.logs];
  }
  addLog(level, message, detail) {
    const entry = {
      timestamp: Date.now(),
      level,
      message,
      detail
    };
    this.logs.unshift(entry);
    if (this.logs.length > 200) {
      this.logs.pop();
    }
  }
  async startSync(silent = false) {
    if (this.state !== "idle" && this.state !== "error") {
      this.addLog("warn", "\u5DF2\u6709\u540C\u6B65\u4EFB\u52A1\u6B63\u5728\u8FD0\u884C\uFF0C\u8DF3\u8FC7\u672C\u6B21\u89E6\u53D1");
      return { success: false, stats: { uploaded: 0, downloaded: 0, deleted: 0, errors: 0 } };
    }
    const settings = this.getSettings();
    if (!settings.accessToken) {
      this.addLog("error", "\u672A\u914D\u7F6E\u767E\u5EA6\u7F51\u76D8\u6388\u6743\uFF0C\u8BF7\u5148\u524D\u5F80\u8BBE\u7F6E\u6388\u6743\u8D26\u53F7");
      this.setState("error", "\u672A\u6388\u6743\u8D26\u53F7");
      return { success: false, stats: { uploaded: 0, downloaded: 0, deleted: 0, errors: 0 } };
    }
    this.filter.updateSettings(settings);
    this.queue.setConcurrency(settings.concurrency || 3);
    const stats = { uploaded: 0, downloaded: 0, deleted: 0, errors: 0 };
    const startTime = Date.now();
    try {
      this.setState("preparing", "\u6B63\u5728\u52A0\u8F7D\u540C\u6B65\u6E05\u5355...");
      await this.manifest.load();
      this.setState("diffing", "\u6B63\u5728\u626B\u63CF\u672C\u5730\u6587\u4EF6...");
      const localFiles = await this.scanLocalFiles();
      this.setState("diffing", "\u6B63\u5728\u68C0\u7D22\u767E\u5EA6\u7F51\u76D8\u6587\u4EF6\u5217\u8868...");
      const remoteFiles = await this.scanRemoteFiles(settings.remoteBasePath);
      this.setState("diffing", "\u6B63\u5728\u5BF9\u6BD4\u5DEE\u5F02\u5E76\u88C1\u51B3\u51B2\u7A81 (LWW)...");
      const plans = SyncPlanner.plan(
        localFiles,
        remoteFiles,
        this.manifest.getAll(),
        settings.remoteBasePath
      );
      if (plans.length === 0) {
        this.addLog("info", "\u4E24\u7AEF\u6587\u4EF6\u5DF2\u5904\u4E8E\u6700\u65B0\u4E00\u81F4\u72B6\u6001\uFF0C\u65E0\u9700\u4F20\u8F93");
        this.setState("idle", "\u540C\u6B65\u5B8C\u6210 (\u65E0\u53D8\u52A8)");
        return { success: true, stats };
      }
      this.addLog("info", `\u89C4\u5212\u5B8C\u6210\uFF0C\u5F85\u6267\u884C\u64CD\u4F5C\u6570: ${plans.length}`);
      this.setState("syncing", `\u540C\u6B65\u4E2D (0/${plans.length})...`);
      let processed = 0;
      for (const item of plans) {
        await this.queue.add(async () => {
          try {
            await this.executePlanItem(item);
            if (item.action === "UPLOAD") stats.uploaded++;
            else if (item.action === "DOWNLOAD") stats.downloaded++;
            else if (item.action === "DELETE_LOCAL" || item.action === "DELETE_REMOTE") stats.deleted++;
          } catch (err) {
            stats.errors++;
            const msg = err instanceof Error ? err.message : String(err);
            this.addLog("error", `\u5904\u7406\u5931\u8D25: ${item.path}`, msg);
          } finally {
            processed++;
            this.setState("syncing", `\u540C\u6B65\u4E2D (${processed}/${plans.length})...`);
          }
        });
      }
      await this.queue.waitAll();
      this.manifest.updateLastSyncTime();
      await this.manifest.save();
      settings.lastSyncTime = Date.now();
      await this.saveSettings(settings);
      const elapsed = ((Date.now() - startTime) / 1e3).toFixed(1);
      const summary = `\u540C\u6B65\u5B8C\u6210\uFF01\u7528\u65F6 ${elapsed}s | \u4E0A\u4F20: ${stats.uploaded}, \u4E0B\u8F7D: ${stats.downloaded}, \u5220\u9664: ${stats.deleted}, \u5931\u8D25: ${stats.errors}`;
      this.addLog(stats.errors > 0 ? "warn" : "success", summary);
      this.setState("idle", "\u540C\u6B65\u5B8C\u6210");
      return { success: stats.errors === 0, stats };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      this.addLog("error", "\u540C\u6B65\u8FC7\u7A0B\u4E2D\u53D1\u751F\u4E25\u91CD\u5F02\u5E38", msg);
      this.setState("error", msg);
      return { success: false, stats };
    }
  }
  async executePlanItem(item) {
    const settings = this.getSettings();
    const adapter = this.app.vault.adapter;
    switch (item.action) {
      case "UPLOAD": {
        if (!await adapter.exists(item.path)) {
          return;
        }
        const buffer = await adapter.readBinary(item.path);
        const stat = await adapter.stat(item.path);
        const localMtime = stat?.mtime || Date.now();
        const res = await this.uploader.uploadFile(item.remotePath, buffer, {
          enableE2EE: settings.enableE2EE,
          e2eePassword: settings.e2eePassword
        });
        this.manifest.set({
          path: item.path,
          remotePath: item.remotePath,
          mtime: localMtime,
          remoteMtime: (res.mtime || Math.floor(Date.now() / 1e3)) * 1e3,
          md5: res.md5 || "",
          size: stat?.size || buffer.byteLength,
          remoteSize: res.size,
          fsId: res.fs_id
        });
        this.addLog("success", `\u4E0A\u4F20\u6210\u529F: ${item.path}`);
        break;
      }
      case "DOWNLOAD": {
        if (!item.remote?.fsId) {
          throw new Error(`\u7F3A\u5C11\u8FDC\u7AEF fs_id\uFF0C\u65E0\u6CD5\u4E0B\u8F7D: ${item.path}`);
        }
        const buffer = await this.downloader.downloadByFsId(item.remote.fsId, {
          e2eePassword: settings.e2eePassword
        });
        const lastSlash = item.path.lastIndexOf("/");
        if (lastSlash > 0) {
          const dir = item.path.substring(0, lastSlash);
          if (!await adapter.exists(dir)) {
            await adapter.mkdir(dir);
          }
        }
        await adapter.writeBinary(item.path, buffer);
        const stat = await adapter.stat(item.path);
        this.manifest.set({
          path: item.path,
          remotePath: item.remotePath,
          mtime: stat?.mtime || Date.now(),
          remoteMtime: item.remote.mtime,
          md5: item.remote.md5 || "",
          size: buffer.byteLength,
          remoteSize: item.remote.size,
          fsId: item.remote.fsId
        });
        this.addLog("success", `\u4E0B\u8F7D\u6210\u529F: ${item.path}`);
        break;
      }
      case "DELETE_LOCAL": {
        if (await adapter.exists(item.path)) {
          const file = this.app.vault.getAbstractFileByPath(item.path);
          if (file && file instanceof import_obsidian4.TFile) {
            await this.app.fileManager.trashFile(file);
          } else {
            await adapter.trashLocal(item.path);
          }
          this.addLog("info", `\u79FB\u5165\u672C\u5730\u56DE\u6536\u7AD9: ${item.path}`);
        }
        this.manifest.delete(item.path);
        break;
      }
      case "DELETE_REMOTE": {
        await this.client.deleteFiles([item.remotePath]);
        this.manifest.delete(item.path);
        this.addLog("info", `\u79FB\u5165\u7F51\u76D8\u56DE\u6536\u7AD9: ${item.path}`);
        break;
      }
      case "CLEAN_MANIFEST": {
        this.manifest.delete(item.path);
        break;
      }
      default:
        break;
    }
  }
  async scanLocalFiles() {
    const adapter = this.app.vault.adapter;
    const result = /* @__PURE__ */ new Map();
    const scanDirectory = async (dir) => {
      const list = await adapter.list(dir);
      for (const file of list.files) {
        if (this.filter.shouldIgnore(file)) {
          continue;
        }
        const stat = await adapter.stat(file);
        if (stat && stat.type === "file") {
          result.set(file, {
            path: file,
            mtime: stat.mtime,
            size: stat.size
          });
        }
      }
      for (const folder of list.folders) {
        if (this.filter.shouldIgnore(folder)) {
          continue;
        }
        await scanDirectory(folder);
      }
    };
    await scanDirectory("");
    const settings = this.getSettings();
    const configDir = this.app.vault.configDir;
    if (settings.syncObsidianConfig && configDir && await adapter.exists(configDir)) {
      await scanDirectory(configDir);
    }
    return result;
  }
  async scanRemoteFiles(remoteBasePath) {
    const result = /* @__PURE__ */ new Map();
    const cleanBase = remoteBasePath.endsWith("/") ? remoteBasePath.slice(0, -1) : remoteBasePath;
    const items = await this.client.listAll(cleanBase);
    for (const item of items) {
      if (item.isdir === 1) {
        continue;
      }
      let relativePath = item.path;
      if (relativePath.startsWith(cleanBase)) {
        relativePath = relativePath.slice(cleanBase.length);
      }
      if (relativePath.startsWith("/")) {
        relativePath = relativePath.slice(1);
      }
      if (this.filter.shouldIgnore(relativePath)) {
        continue;
      }
      result.set(relativePath, {
        path: relativePath,
        remotePath: item.path,
        mtime: (item.server_mtime || 0) * 1e3,
        size: item.size || 0,
        fsId: item.fs_id,
        md5: item.md5
      });
    }
    return result;
  }
};

// src/ui/statusBar.ts
var StatusBarManager = class {
  constructor(statusBarItem, engine, onClick) {
    this.engine = engine;
    this.onClick = onClick;
    this.statusBarEl = statusBarItem;
    this.statusBarEl.addClass("baidu-sync-status-bar");
    this.statusBarEl.addEventListener("click", () => this.onClick());
    this.engine.onStateChange((state, msg) => {
      this.updateState(state, msg);
    });
    this.updateState("idle", "\u7A7A\u95F2");
  }
  updateState(state, message) {
    let icon = "\u2601\uFE0F";
    let text = message || "\u5C31\u7EEA";
    switch (state) {
      case "idle":
        icon = "\u2601\uFE0F";
        break;
      case "preparing":
      case "diffing":
      case "syncing":
        icon = "\u{1F504}";
        break;
      case "error":
        icon = "\u26A0\uFE0F";
        break;
    }
    this.statusBarEl.setText(`${icon} \u7F51\u76D8: ${text}`);
  }
};

// src/ui/logModal.ts
var import_obsidian5 = require("obsidian");
var SyncLogModal = class extends import_obsidian5.Modal {
  constructor(app, engine) {
    super(app);
    this.engine = engine;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("baidu-sync-log-modal");
    new import_obsidian5.Setting(contentEl).setName("\u767E\u5EA6\u7F51\u76D8\u540C\u6B65\u65E5\u5FD7").setHeading();
    new import_obsidian5.Setting(contentEl).setName("\u7ACB\u5373\u6267\u884C\u540C\u6B65").setDesc("\u624B\u52A8\u89E6\u53D1\u5168\u91CF\u5BF9\u6BD4\u4E0E\u589E\u91CF\u53CC\u5411\u540C\u6B65").addButton((btn) => {
      btn.setButtonText("\u5F00\u59CB\u540C\u6B65").setCta().onClick(async () => {
        btn.setDisabled(true);
        await this.engine.startSync(false);
        btn.setDisabled(false);
        this.renderLogs(container);
      });
    });
    const container = contentEl.createDiv({ cls: "baidu-sync-log-container" });
    this.renderLogs(container);
  }
  renderLogs(container) {
    container.empty();
    const logs = this.engine.getLogs();
    if (logs.length === 0) {
      container.createEl("p", {
        text: "\u6682\u65E0\u540C\u6B65\u65E5\u5FD7\u8BB0\u5F55",
        cls: "baidu-sync-log-row info"
      });
      return;
    }
    for (const log of logs) {
      const row = container.createDiv({
        cls: `baidu-sync-log-row ${log.level}`
      });
      const timeStr = new Date(log.timestamp).toLocaleTimeString();
      const left = row.createDiv();
      left.createSpan({ text: `[${timeStr}] `, cls: "log-time" });
      left.createSpan({ text: log.message, cls: "log-msg" });
      if (log.detail) {
        row.createDiv({ text: log.detail, cls: "log-detail" });
      }
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var BaiduSyncPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.intervalId = null;
    this.saveDebounceTimer = null;
    this.ribbonIconEl = null;
  }
  async onload() {
    await this.loadSettings();
    const configDir = this.app.vault.configDir;
    const manifestPath = `${this.manifest.dir || `${configDir}/plugins/baidu-netdisk-sync`}/sync_manifest.json`;
    this.manifestMgr = new ManifestManager(this.app.vault.adapter, manifestPath);
    this.oauth = new BaiduOAuthManager(
      () => this.settings,
      async (s) => {
        this.settings = s;
        await this.saveData(this.settings);
      }
    );
    this.client = new BaiduClient(this.oauth);
    this.engine = new SyncEngine(
      this.app,
      () => this.settings,
      async (s) => {
        this.settings = s;
        await this.saveData(this.settings);
      },
      this.client,
      this.manifestMgr
    );
    const statusBarItem = this.addStatusBarItem();
    this.statusBar = new StatusBarManager(statusBarItem, this.engine, () => {
      new SyncLogModal(this.app, this.engine).open();
    });
    this.ribbonIconEl = this.addRibbonIcon("cloud", "\u767E\u5EA6\u7F51\u76D8\u540C\u6B65", async () => {
      new import_obsidian6.Notice("\u6B63\u5728\u542F\u52A8\u767E\u5EA6\u7F51\u76D8\u540C\u6B65...");
      const res = await this.engine.startSync(false);
      if (res.success) {
        new import_obsidian6.Notice("\u767E\u5EA6\u7F51\u76D8\u540C\u6B65\u5B8C\u6210\uFF01");
      } else {
        new import_obsidian6.Notice("\u767E\u5EA6\u7F51\u76D8\u540C\u6B65\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5\u540C\u6B65\u65E5\u5FD7");
      }
    });
    this.engine.onStateChange((state) => {
      if (this.ribbonIconEl) {
        if (state === "syncing" || state === "diffing" || state === "preparing") {
          this.ribbonIconEl.addClass("baidu-sync-spinning");
        } else {
          this.ribbonIconEl.removeClass("baidu-sync-spinning");
        }
      }
    });
    this.addCommand({
      id: "baidu-sync-now",
      name: "\u7ACB\u5373\u6267\u884C\u540C\u6B65 (Sync Now)",
      callback: async () => {
        new import_obsidian6.Notice("\u6B63\u5728\u542F\u52A8\u767E\u5EA6\u7F51\u76D8\u540C\u6B65...");
        await this.engine.startSync(false);
      }
    });
    this.addCommand({
      id: "baidu-sync-view-logs",
      name: "\u67E5\u770B\u540C\u6B65\u65E5\u5FD7 (View Sync Logs)",
      callback: () => {
        new SyncLogModal(this.app, this.engine).open();
      }
    });
    this.addSettingTab(new BaiduSyncSettingTab(this.app, this));
    this.setupTriggers();
  }
  onunload() {
    if (this.intervalId !== null) {
      window.clearInterval(this.intervalId);
      this.intervalId = null;
    }
    if (this.saveDebounceTimer !== null) {
      window.clearTimeout(this.saveDebounceTimer);
      this.saveDebounceTimer = null;
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  resetInterval() {
    if (this.intervalId !== null) {
      window.clearInterval(this.intervalId);
      this.intervalId = null;
    }
    if (this.settings.syncIntervalMinutes > 0) {
      const ms = this.settings.syncIntervalMinutes * 60 * 1e3;
      this.intervalId = window.setInterval(async () => {
        if (this.settings.accessToken) {
          await this.engine.startSync(true);
        }
      }, ms);
    }
  }
  setupTriggers() {
    if (this.settings.syncOnStartup && this.settings.accessToken) {
      window.setTimeout(async () => {
        await this.engine.startSync(true);
      }, 3e3);
    }
    this.resetInterval();
    const onVaultChange = (file) => {
      if (!this.settings.syncOnSave || !this.settings.accessToken) return;
      if (this.engine.isSyncing()) return;
      if (file.path.includes("sync_manifest.json") || file.path.includes("workspace")) return;
      if (this.saveDebounceTimer !== null) {
        window.clearTimeout(this.saveDebounceTimer);
      }
      const debounceMs = (this.settings.syncDebounceSeconds || 5) * 1e3;
      this.saveDebounceTimer = window.setTimeout(async () => {
        await this.engine.startSync(true);
      }, debounceMs);
    };
    this.registerEvent(this.app.vault.on("modify", onVaultChange));
    this.registerEvent(this.app.vault.on("create", onVaultChange));
    this.registerEvent(this.app.vault.on("delete", onVaultChange));
  }
};
